version: '3.8'
services:
  db:
    container_name: code-racer-postgres
    image: postgres:15.3-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
