name: Deploy
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: "Install Dependencies"
        run: npm i
      - run: "fly deploy --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --config packages/wss/fly.toml --dockerfile packages/wss/Dockerfile"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
