name: Deploy WSS
on:
  push:
    branches:
      - main
jobs:
  deploy-wss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: "fly deploy --remote-only --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --config packages/wss/fly.toml --dockerfile packages/wss/Dockerfile"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
