name: Deploy
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: "Install Dependencies"
        run: npm i
      - name: "Update Database"
        run: DATABASE_URL=${{ secrets.DATABASE_URL }} npx prisma db push
      - run: "flyctl deploy --remote-only
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}
          --build-arg GITHUB_CLIENT_ID=${{ secrets._GITHUB_CLIENT_ID }}
          --build-arg GITHUB_CLIENT_SECRET=${{ secrets._GITHUB_CLIENT_SECRET }}
          --build-arg NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
          --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
